# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 516afde39d515b7a42e3433203a7aacd1bc913fc9c498c150c21585522322334f2e924064adafab69ac66f92598280de3176924e555a56008878ec7b58595131

test:
  secret_key_base: 4faf49e05e9cd3c58d59f786215508fa326fae0120553fc0f7e92e1b340e64a4340604cb71f38dc10c0a180e51ae47f6490c6defd1cc2e3eb3805dbdfcfdf837

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
